"""Build deterministic offline web assets. No runtime/filesystem dependency on device."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]

def generate():
    lines = ['// Generated by tools/embed_web.py; edit web/ instead.', '#pragma once', '#include <Arduino.h>']
    for name in ('index.html', 'style.css', 'app.js'):
        data = (ROOT / 'web' / name).read_bytes()
        symbol = 'web_' + name.replace('.', '_')
        lines.append(f'static const uint8_t {symbol}[] PROGMEM = {{')
        for start in range(0, len(data), 24):
            lines.append('  ' + ','.join(str(x) for x in data[start:start+24]) + ',')
        lines.extend(['};', f'static const size_t {symbol}_len = {len(data)};'])
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'firmware' / 'RehabEsp32' / 'src' / 'web_assets.h'
    expected = generate()
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != expected:
            raise SystemExit('Embedded assets differ; run tools/embed_web.py')
    else:
        target.write_text(expected, encoding='utf-8', newline='\n')
        print(f'Embedded 3 web assets ({len(expected)} generated bytes)')
